
TmallDemo:
  swagger-open: true                #是否开启swagger (true/false)
  kaptcha-open: false               #是否开启登录时验证码 (true/false)
  spring-session-open: true        #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900  #多久检测一次失效的session(只在单机环境下生效) 单位：秒
  muti-datasource-open: true  #开启多数据源
  file-upload-path: E:/tmall #上传目录

beetl:
  resource-auto-check: true         #热加载beetl模板，开发时候用

spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /WEB-INF/page/
      suffix: .jsp
      static-path-pattern: /res/*
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      additional-exclude: /res/*
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

